don't build game.libretro.daphne from kodi-game repo
The daphne package currently fails to build in my Debian Forky
container with error messages like this:
  daphne/src/audio/SDL_audiocvt.c:955:36: error: implicit declaration of function 'ceil' [-Wimplicit-function-declaration]
and
  daphne/daphne-1.0-src/vldp2/vldp/vldp_internal.c:852:31: error: implicit declaration of function 'fileno' [-Wimplicit-function-declaration]

There is a PR at https://github.com/libretro/daphne/pull/51 which might fix
these problems. Let's just disable this emulator until the PR is merged.