don't build game.libretro.dosbox-core from kodi-game repo
The dosbox-core package currently fails to build in my Debian Forky
container with error messages like this:
  /kodi/build/addons_kodigame_build_build/dosbox-core/src/dosbox-core/libretro/deps/mpg123/src/compat/compat.c:500:27: error: assignment to '__sighandler_t' {aka 'void (*)(int)'} from incompatible pointer type 'void (*)(void)' [-Wincompatible-pointer-types]

According to https://github.com/kodi-game/game.libretro.dosbox-core this
addon is deprecated anyway, so let's just disable this emulator.