don't build game.libretro.beetle-bsnes, due to build failure
Building currently fails with:
  ./mednafen/snes/src/lib/nall/string/base.hpp:37:15: error: 'size_t strlcpy(char*, const char*, size_t)' redeclared inline without 'gnu_inline' attribute

Other projects (e.g. https://github.com/NixOS/nixpkgs/pull/263751) have
already disabled this emulator because it is old and not really maintained;
so let's disable it here as well.