don't build game.libretro.dolphin from kodi-game repo
The dolphin package currently fails to build in my Debian Forky
container with error messages like this:
  /kodi/build/addons_kodigame_build2_build/dolphin/src/dolphin/Source/Core/Core/IOS/FS/FileSystemProxy.cpp:275:12:   required from here
  /usr/include/fmt/core.h:1576:63: error: 'fmt::v10::detail::type_is_unformattable_for<const IOS::HLE::SeekMode, char> _' has incomplete type

I don't want to further debug this at the moment, so let's just disable
this emulator.