don't build game.libretro.tyrquake from kodi-game repo
The tyrquake package currently fails to build in my Debian Forky container
with error messages like this:
  common/qtypes.h:36:15: error: cannot use keyword 'false' as enumeration constant

This appears to be the same problem as reported in the comment at
https://github.com/libretro/tyrquake/pull/135#issuecomment-3475780980 ,
which is not fixed yet. So let's just disable this emulator for now.