build official addons without parallelism
This is a workaround for occasional linker errors in inputstream.adaptive.
That addon depends on NlohmannJSON package in version 3.12.0, while other
addons depend on NlohmannJSON package in older versions (e.g. pvr.freebox
depends on version 3.10.2); and if both versions of NlohmannJSON are built
and installed in parallel, they probably overwrite the file
addons_official_build_build/depends/include/nlohmann/json.hpp with different
versions. And if this conflict is timed badly, it is probably the reason for
linker errors like
  HelperWv.cpp:(.text+0x6c0e): undefined reference to `UTILS::JSON::GetValueAtPath(nlohmann::json_abi_v3_12_0::basic_json<...
when building inputstream.adaptive_test.