don't build game.libretro.flycast from kodi-game repo
The flycast package currently fails to build in my Debian Forky container
with error messages like this:
  core/deps/libzip/mkstemp.c:70:15: error: implicit declaration of function 'getpid' [-Wimplicit-function-declaration]

I don't want to debug this at the moment, so let's just disable this
emulator.

This specific problem was apparently already reported at
https://github.com/libretro/flycast/issues/1194 . But it looks like the
code used in this addon (https://github.com/kodi-game/flycast/) and also
its parent fork (https://github.com/libretro/flycast) are deprecated, and
the repo at https://github.com/flyinghead/flycast should be used instead.